[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

# For Single Page Applications
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables
[build.environment]
  NODE_VERSION = "18"
  
# For Next.js API routes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# For handling client-side routing
[[redirects]]
  from = "/*"
  to = "/.next/server/pages/404.html"
  status = 404

# Stop Netlify from attempting to process our API requests
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization"
