[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

# Environment variables
[build.environment]
  NODE_VERSION = "18"

# Redirect for API routes
[[redirects]]
  from = "/.netlify/functions/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

# For handling client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API headers for CORS
[[headers]]
  for = "/.netlify/functions/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization"
