[build]
  command = "npm run build"
  publish = ".next"

# Environment variables
[build.environment]
  NODE_VERSION = "18"
  NEXT_PUBLIC_IS_NETLIFY = "true"

# For handling client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Fallback for API endpoints since we're using client-side mock data
[[redirects]]
  from = "/api/*"
  to = "/index.html"
  status = 200

# For Next.js static assets
[[headers]]
  for = "/_next/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
